### ISSUE TITLE
Build error: Unknown CMake command "METNO_HEADERS".

### ISSUE THREAD

**Issue by erikthysell** [metno/diana#18]
When trying to build (LinuxMint 20, cmake 3.16) it throws this error:
CMake Error at CMakeLists.txt:466 (METNO_HEADERS):
  Unknown CMake command "METNO_HEADERS".

(both with master branch as well as tag 3.40.0a1-1)
How would I fix this?

**Comment by alexander-buerger-met-no** [comment]
Could you specify the exact cmake build command including the directory you run from?

**Comment by erikthysell** [comment]
DI tried to follow your README instructions:
SRC=/home/"username"/Temp/diana-master/source
BLD=/home/"username"/build
INS=/home/"username"/Diana/

cd "$BLD"
cmake \
    -DCMAKE_INSTALL_PREFIX="$INS" \
    -DENABLE_DIANA_OMP=1 \
    -DENABLE_PERL=1 \
    -DENABLE_OBS_BUFR=1 \
    -DENABLE_GEOTIFF=1 \
    "$SRC"

**Comment by alexander-buerger-met-no** [comment]
Did you add "\" or put all of the cmake command on one line?

**Comment by erikthysell** [comment]
I just simply copied and pasted the whole paragraph.. in one go that results in the following line (when afterwards going arrow up):

> cmake         -DCMAKE_INSTALL_PREFIX="$INS"         -DENABLE_DIANA_OMP=1         -DENABLE_PERL=1         -DENABLE_OBS_BUFR=1         -DENABLE_GEOTIFF=1         "$SRC"

**Comment by alexander-buerger-met-no** [comment]
Could you check that `$SRC` is the top level directory, i.e. the directory with the `README.md` file containging the build instructions?

**Comment by erikthysell** [comment]
First I tried with the diana-master/src folder but changing to diana-master directory (where README.md is) makes no difference

**Comment by alexander-buerger-met-no** [comment]
It must be the one with `README.md`. Did you try with `$SRC` set to that directory and starting from a completely empty `$BLD` directory?

**Comment by erikthysell** [comment]
Yes and yes...

**Comment by alexander-buerger-met-no** [comment]
I am unable to reproduce the problem at this time.
